// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAeBHn_46UytppNwb4n7MlcCsN5fhDTRk',
    appId: '1:1095732968181:web:d73a65aca12173128d63bc',
    messagingSenderId: '1095732968181',
    projectId: 'expenses-4e660',
    authDomain: 'expenses-4e660.firebaseapp.com',
    storageBucket: 'expenses-4e660.appspot.com',
    measurementId: 'G-N7EK8D7XJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVLZRoYYQnQNcSQMVwB_LxNNyR4AM1Umg',
    appId: '1:1095732968181:android:630a1bda7624e3448d63bc',
    messagingSenderId: '1095732968181',
    projectId: 'expenses-4e660',
    storageBucket: 'expenses-4e660.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs22Dlc1FBoDqoi7yZmqfsAI85WIG6Dsc',
    appId: '1:1095732968181:ios:a04de2974572b7598d63bc',
    messagingSenderId: '1095732968181',
    projectId: 'expenses-4e660',
    storageBucket: 'expenses-4e660.appspot.com',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs22Dlc1FBoDqoi7yZmqfsAI85WIG6Dsc',
    appId: '1:1095732968181:ios:a04de2974572b7598d63bc',
    messagingSenderId: '1095732968181',
    projectId: 'expenses-4e660',
    storageBucket: 'expenses-4e660.appspot.com',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAeBHn_46UytppNwb4n7MlcCsN5fhDTRk',
    appId: '1:1095732968181:web:bea684a488ab013c8d63bc',
    messagingSenderId: '1095732968181',
    projectId: 'expenses-4e660',
    authDomain: 'expenses-4e660.firebaseapp.com',
    storageBucket: 'expenses-4e660.appspot.com',
    measurementId: 'G-EEDT4HLGW0',
  );

}